import type { CheckDefinition } from "./types";

/**
 * All diagnosis/survey question data lives here as plain objects — add or
 * edit a question by editing this array, no UI code changes needed.
 */
export const CHECK_DEFINITIONS: CheckDefinition[] = [
  {
    id: "job-fit",
    kind: "diagnosis",
    title: "직업 적성 검사",
    description: "나에게 잘 맞는 직무와 업무 성향을 확인해 보세요.",
    duration: "약 10분",
    tag: "직무 추천",
    scoring: "archetype-tally",
    archetypes: {
      analysis: {
        title: "분석·기획형",
        description: "정보를 꼼꼼히 살피고 체계적으로 계획을 세우는 데 강점이 있어요.",
        keywords: ["데이터 분석", "기획", "전략 수립"],
      },
      dev: {
        title: "개발·문제 해결형",
        description: "직접 부딪히며 문제를 해결하는 실행력이 강점이에요.",
        keywords: ["문제 해결", "실행력", "기술 직무"],
      },
      social: {
        title: "소통·협업형",
        description: "사람과의 관계와 협업 속에서 힘을 발휘해요.",
        keywords: ["협업", "커뮤니케이션", "고객 응대"],
      },
      creative: {
        title: "창의·콘텐츠형",
        description: "새로운 아이디어와 표현으로 가치를 만들어내요.",
        keywords: ["기획 아이디어", "콘텐츠 제작", "브랜딩"],
      },
    },
    questions: [
      {
        id: "q1",
        text: "새로운 과제를 받았을 때 가장 먼저 하고 싶은 행동은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "관련 자료를 조사한다", archetype: "analysis" },
          { value: "b", label: "바로 직접 시도해 본다", archetype: "dev" },
          { value: "c", label: "팀원과 아이디어를 나눈다", archetype: "social" },
          { value: "d", label: "전체 계획부터 정리한다", archetype: "analysis" },
        ],
      },
      {
        id: "q2",
        text: "가장 몰입하기 쉬운 활동은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "문제를 분석하고 해결하는 일", archetype: "dev" },
          { value: "b", label: "사람과 소통하고 설득하는 일", archetype: "social" },
          { value: "c", label: "새로운 아이디어를 만드는 일", archetype: "creative" },
          { value: "d", label: "자료를 정리하고 체계를 만드는 일", archetype: "analysis" },
        ],
      },
      {
        id: "q3",
        text: "결과물을 만들 때 더 중요하게 생각하는 것은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "정확성", archetype: "analysis" },
          { value: "b", label: "창의성", archetype: "creative" },
          { value: "c", label: "사용자 만족", archetype: "social" },
          { value: "d", label: "효율성", archetype: "dev" },
        ],
      },
      {
        id: "q4",
        text: "선호하는 업무 방식은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "혼자 깊게 집중하는 방식", archetype: "dev" },
          { value: "b", label: "팀과 자주 의견을 나누는 방식", archetype: "social" },
          { value: "c", label: "정해진 절차에 따라 진행하는 방식", archetype: "analysis" },
          { value: "d", label: "새로운 방법을 직접 만들어 보는 방식", archetype: "creative" },
        ],
      },
      {
        id: "q5",
        text: "문제가 생겼을 때 나의 대응은 어떤 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "원인을 하나씩 분석해본다", archetype: "analysis" },
          { value: "b", label: "일단 여러 방법을 시도해본다", archetype: "dev" },
          { value: "c", label: "주변에 물어보고 힌트를 얻는다", archetype: "social" },
          { value: "d", label: "다른 관점에서 새롭게 접근해본다", archetype: "creative" },
        ],
      },
      {
        id: "q6",
        text: "칭찬받을 때 가장 기분 좋은 말은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "꼼꼼하고 정확하네요", archetype: "analysis" },
          { value: "b", label: "문제를 잘 해결하네요", archetype: "dev" },
          { value: "c", label: "함께 일하기 편하네요", archetype: "social" },
          { value: "d", label: "아이디어가 참신하네요", archetype: "creative" },
        ],
      },
      {
        id: "q7",
        text: "결과물을 준비할 때 나의 습관에 가장 가까운 것은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "데이터와 근거를 꼼꼼히 정리한다", archetype: "analysis" },
          { value: "b", label: "일단 완성본을 만들고 다듬는다", archetype: "dev" },
          { value: "c", label: "동료 의견을 먼저 들어본다", archetype: "social" },
          { value: "d", label: "다른 사례를 참고해 새롭게 구성한다", archetype: "creative" },
        ],
      },
      {
        id: "q8",
        text: "팀 프로젝트에서 내가 자주 맡는 역할은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "일정과 기획을 정리하는 역할", archetype: "analysis" },
          { value: "b", label: "실제 결과물을 만드는 역할", archetype: "dev" },
          { value: "c", label: "팀원 간 조율을 돕는 역할", archetype: "social" },
          { value: "d", label: "새로운 방향을 제안하는 역할", archetype: "creative" },
        ],
      },
    ],
  },
  {
    id: "workplace-fit",
    kind: "diagnosis",
    title: "직장 적성 검사",
    description: "내가 편하게 일할 수 있는 조직 문화와 업무 환경을 알아보세요.",
    duration: "약 8분",
    tag: "조직 문화",
    scoring: "archetype-tally",
    archetypes: {
      stable: {
        title: "안정적·체계적 환경 선호",
        description: "명확한 규칙과 절차 안에서 안정적으로 일할 때 편안함을 느껴요.",
        keywords: ["체계적 업무", "명확한 가이드", "안정적 조직문화"],
      },
      autonomous: {
        title: "자율적·유연한 환경 선호",
        description: "스스로 방향을 정하고 자율적으로 일할 때 능률이 올라가요.",
        keywords: ["자율 근무", "독립적 업무", "유연한 문화"],
      },
      collab: {
        title: "협업 중심 환경 선호",
        description: "함께 의견을 나누고 협력할 때 힘을 발휘해요.",
        keywords: ["팀워크", "수평적 소통", "협업 중심"],
      },
      challenge: {
        title: "도전·성장 중심 환경 선호",
        description: "빠른 변화와 새로운 도전 속에서 성장하는 걸 즐겨요.",
        keywords: ["빠른 성장", "도전적 과제", "변화 적응"],
      },
    },
    questions: [
      {
        id: "q1",
        text: "선호하는 업무 환경은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "조용하고 집중하기 좋은 환경", archetype: "autonomous" },
          { value: "b", label: "자유롭게 대화가 가능한 환경", archetype: "collab" },
          { value: "c", label: "역할이 명확하게 나뉜 환경", archetype: "stable" },
          { value: "d", label: "빠르게 변화하고 도전적인 환경", archetype: "challenge" },
        ],
      },
      {
        id: "q2",
        text: "일을 진행할 때 더 편한 방식은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "명확한 가이드가 있는 방식", archetype: "stable" },
          { value: "b", label: "스스로 방향을 정할 수 있는 방식", archetype: "autonomous" },
          { value: "c", label: "팀원과 함께 결정하는 방식", archetype: "collab" },
          { value: "d", label: "빠르게 시도하고 수정하는 방식", archetype: "challenge" },
        ],
      },
      {
        id: "q3",
        text: "피드백을 받을 때 선호하는 방식은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "구체적이고 정리된 피드백", archetype: "stable" },
          { value: "b", label: "자주 가볍게 주고받는 피드백", archetype: "collab" },
          { value: "c", label: "결과물 중심의 피드백", archetype: "autonomous" },
          { value: "d", label: "자유로운 토론 방식의 피드백", archetype: "challenge" },
        ],
      },
      {
        id: "q4",
        text: "업무 성과를 평가받을 때 더 편안한 기준은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "정해진 기준과 규정에 따른 평가", archetype: "stable" },
          { value: "b", label: "스스로 세운 목표 대비 평가", archetype: "autonomous" },
          { value: "c", label: "팀 전체 성과 중심의 평가", archetype: "collab" },
          { value: "d", label: "새로운 시도와 성장 중심의 평가", archetype: "challenge" },
        ],
      },
      {
        id: "q5",
        text: "회의나 협업 상황에서 나는 어떤 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "정리된 안건대로 진행되는 걸 선호", archetype: "stable" },
          { value: "b", label: "자유롭게 의견을 나누는 걸 선호", archetype: "collab" },
          { value: "c", label: "각자 역할에 집중하는 걸 선호", archetype: "autonomous" },
          { value: "d", label: "새로운 시도를 제안하는 걸 선호", archetype: "challenge" },
        ],
      },
      {
        id: "q6",
        text: "변화가 생겼을 때 나의 반응은 어떤 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "안정적으로 기존 방식을 유지하고 싶다", archetype: "stable" },
          { value: "b", label: "나만의 방식으로 적응해본다", archetype: "autonomous" },
          { value: "c", label: "팀과 상의하며 함께 적응한다", archetype: "collab" },
          { value: "d", label: "오히려 변화가 반갑고 기대된다", archetype: "challenge" },
        ],
      },
    ],
  },
  {
    id: "personality",
    kind: "diagnosis",
    title: "성격 유형 검사",
    description: "나의 성격 특성과 소통 방식을 바탕으로 취업 준비 방향을 찾아보세요.",
    duration: "약 7분",
    tag: "자기 이해",
    scoring: "archetype-tally",
    archetypes: {
      evidence: {
        title: "신중·근거중심형",
        description: "충분한 근거와 자료를 바탕으로 신중하게 판단해요.",
        keywords: ["신중함", "근거 기반 판단", "꼼꼼함"],
      },
      intuition: {
        title: "직관·감각중심형",
        description: "상황의 흐름과 직감을 바탕으로 유연하게 대응해요.",
        keywords: ["유연함", "직관적 판단", "적응력"],
      },
      relational: {
        title: "관계·소통중심형",
        description: "주변 사람과의 관계와 소통을 중요하게 생각해요.",
        keywords: ["공감", "소통", "관계 지향"],
      },
      action: {
        title: "실행·행동중심형",
        description: "고민보다 행동을 통해 답을 찾아가요.",
        keywords: ["실행력", "추진력", "현장 중심"],
      },
    },
    questions: [
      {
        id: "q1",
        text: "중요한 결정을 내릴 때 더 자주 사용하는 방식은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "자료와 근거를 충분히 확인한다", archetype: "evidence" },
          { value: "b", label: "직감과 경험을 참고한다", archetype: "intuition" },
          { value: "c", label: "주변 사람의 의견을 들어본다", archetype: "relational" },
          { value: "d", label: "직접 해보며 판단한다", archetype: "action" },
        ],
      },
      {
        id: "q2",
        text: "새로운 사람들과 함께할 때 나는 보통 어떤 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "먼저 분위기를 살핀다", archetype: "evidence" },
          { value: "b", label: "먼저 말을 걸고 대화를 시작한다", archetype: "relational" },
          { value: "c", label: "필요한 말만 간단히 한다", archetype: "action" },
          { value: "d", label: "역할이 정해지면 적극적으로 참여한다", archetype: "intuition" },
        ],
      },
      {
        id: "q3",
        text: "일정 관리 방식은 어떤 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "미리 세부 계획을 세운다", archetype: "evidence" },
          { value: "b", label: "큰 틀만 정하고 상황에 맞춰 조절한다", archetype: "intuition" },
          { value: "c", label: "마감이 가까워질수록 집중한다", archetype: "action" },
          { value: "d", label: "주변 일정에 맞춰 움직인다", archetype: "relational" },
        ],
      },
      {
        id: "q4",
        text: "갈등 상황이 생겼을 때 나는 어떻게 하나요?",
        type: "single",
        options: [
          { value: "a", label: "원인과 사실관계를 먼저 파악한다", archetype: "evidence" },
          { value: "b", label: "감정과 분위기를 먼저 살핀다", archetype: "intuition" },
          { value: "c", label: "상대방 의견을 충분히 들어본다", archetype: "relational" },
          { value: "d", label: "빠르게 해결책을 제시하고 행동한다", archetype: "action" },
        ],
      },
      {
        id: "q5",
        text: "새로운 정보를 받아들일 때 나는 어떤 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "출처와 신뢰도를 꼼꼼히 따진다", archetype: "evidence" },
          { value: "b", label: "전체적인 느낌으로 판단한다", archetype: "intuition" },
          { value: "c", label: "다른 사람은 어떻게 생각하는지 궁금하다", archetype: "relational" },
          { value: "d", label: "일단 적용해보고 판단한다", archetype: "action" },
        ],
      },
      {
        id: "q6",
        text: "스트레스를 받을 때 나는 어떻게 푸는 편인가요?",
        type: "single",
        options: [
          { value: "a", label: "원인을 분석해서 해결하려 한다", archetype: "evidence" },
          { value: "b", label: "기분 전환이 될 만한 걸 찾는다", archetype: "intuition" },
          { value: "c", label: "주변 사람과 이야기하며 푼다", archetype: "relational" },
          { value: "d", label: "몸을 움직이거나 뭔가를 해본다", archetype: "action" },
        ],
      },
      {
        id: "q7",
        text: "대화할 때 나의 스타일에 가장 가까운 것은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "사실과 근거를 중심으로 이야기한다", archetype: "evidence" },
          { value: "b", label: "떠오르는 생각을 자유롭게 이야기한다", archetype: "intuition" },
          { value: "c", label: "상대방 반응을 살피며 이야기한다", archetype: "relational" },
          { value: "d", label: "결론부터 간결하게 이야기한다", archetype: "action" },
        ],
      },
      {
        id: "q8",
        text: "준비 과정에서 나에게 더 중요한 것은 무엇인가요?",
        type: "single",
        options: [
          { value: "a", label: "꼼꼼한 자료 조사", archetype: "evidence" },
          { value: "b", label: "자연스러운 흐름과 감", archetype: "intuition" },
          { value: "c", label: "함께 준비하는 사람들과의 호흡", archetype: "relational" },
          { value: "d", label: "실전 연습과 실행", archetype: "action" },
        ],
      },
    ],
  },
  {
    id: "stress",
    kind: "diagnosis",
    title: "취업 준비 스트레스 진단",
    description:
      "현재 취업 준비 과정에서 느끼는 부담을 가볍게 점검하는 자가 체크예요.",
    duration: "약 5분",
    tag: "마음 건강",
    scoring: "likert-sum",
    questions: [
      {
        id: "q1",
        text: "취업 준비를 생각하면 시작하기 전부터 부담감을 느낀다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
      {
        id: "q2",
        text: "결과가 잘 나오지 않을 때 스스로를 지나치게 부정적으로 평가하게 된다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
      {
        id: "q3",
        text: "주변 사람과 비교하면서 조급함을 느낀다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
      {
        id: "q4",
        text: "취업 준비 때문에 쉬는 시간에도 마음이 편하지 않다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
      {
        id: "q5",
        text: "혼자 고민을 정리하기 어렵다고 느낀다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
      {
        id: "q6",
        text: "자려고 누워도 취업 걱정이 계속 떠오른다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
      {
        id: "q7",
        text: "작은 실수에도 크게 위축된다.",
        type: "scale",
        scaleMax: 3,
        scaleLabels: ["전혀 그렇지 않다", "매우 자주 그렇다"],
        options: [
          { value: "0", label: "전혀 그렇지 않다" },
          { value: "1", label: "가끔 그렇다" },
          { value: "2", label: "자주 그렇다" },
          { value: "3", label: "매우 자주 그렇다" },
        ],
      },
    ],
  },
  {
    id: "current-concerns",
    kind: "survey",
    title: "현재 고민사항 설문",
    description: "요즘 가장 크게 느끼는 고민을 알려주시면 대화와 추천에 반영할게요.",
    duration: "약 3분",
    tag: "권장: 매주 월요일",
    scoring: "participation",
    questions: [
      { id: "q1", text: "현재 가장 큰 고민은 무엇인가요?", type: "text", placeholder: "자유롭게 적어주세요" },
      { id: "q2", text: "취업 준비에서 가장 막히는 부분은 무엇인가요?", type: "text", placeholder: "예: 서류 작성, 면접 준비 등" },
      { id: "q3", text: "지금 가장 필요한 도움은 무엇인가요?", type: "text", placeholder: "자유롭게 적어주세요" },
    ],
  },
  {
    id: "job-status",
    kind: "survey",
    title: "취업 상태 확인 설문",
    description: "현재 구직 활동 단계를 확인하고 맞춤 정보를 조정해 드려요.",
    duration: "약 3분",
    tag: "마감: 이번 달 말",
    scoring: "participation",
    questions: [
      {
        id: "q1",
        text: "현재 취업 준비 단계는 어디인가요?",
        type: "single",
        options: [
          { value: "explore", label: "진로 탐색" },
          { value: "research", label: "취업 정보 탐색" },
          { value: "docs", label: "서류 준비" },
          { value: "interview", label: "면접 준비" },
          { value: "applying", label: "지원 진행 중" },
          { value: "done", label: "취업 완료" },
        ],
      },
      {
        id: "q2",
        text: "최근 지원 경험이 있나요?",
        type: "single",
        options: [
          { value: "yes", label: "있음" },
          { value: "no", label: "없음" },
        ],
      },
      { id: "q3", text: "이번 달 목표가 있나요?", type: "text", placeholder: "자유롭게 적어주세요 (선택)" },
    ],
  },
  {
    id: "support-needs",
    kind: "survey",
    title: "필요한 지원 조사",
    description: "어떤 종류의 지원이 가장 필요한지 알려주세요.",
    duration: "약 3분",
    tag: "권장: 2주에 한 번",
    scoring: "participation",
    questions: [
      {
        id: "q1",
        text: "받고 싶은 지원 형태를 선택해주세요. (복수 선택 가능)",
        type: "multi",
        options: [
          { value: "resume", label: "이력서·자기소개서 피드백" },
          { value: "interview", label: "면접 준비" },
          { value: "job-info", label: "직무 정보" },
          { value: "mental-care", label: "멘탈케어" },
          { value: "lecture", label: "취업 특강" },
          { value: "policy", label: "청년 지원 정책" },
          { value: "hiring", label: "채용 정보" },
        ],
      },
      {
        id: "q2",
        text: "선호하는 프로그램 형식은 무엇인가요?",
        type: "single",
        options: [
          { value: "online", label: "온라인" },
          { value: "offline", label: "오프라인" },
          { value: "1on1", label: "1:1 상담" },
          { value: "group", label: "단체 프로그램" },
        ],
      },
      {
        id: "q3",
        text: "선호하는 참여 시간대는 언제인가요?",
        type: "single",
        options: [
          { value: "weekday-am", label: "평일 오전" },
          { value: "weekday-pm", label: "평일 오후" },
          { value: "weekday-eve", label: "평일 저녁" },
          { value: "weekend", label: "주말" },
        ],
      },
    ],
  },
  {
    id: "feedback",
    kind: "survey",
    title: "서비스 이용 후기",
    description: "마음곁을 이용하며 느낀 점을 자유롭게 남겨주세요.",
    duration: "약 3분",
    tag: "상시 참여 가능",
    scoring: "participation",
    questions: [
      {
        id: "q1",
        text: "서비스 이용 만족도를 알려주세요.",
        type: "scale",
        scaleMax: 4,
        scaleLabels: ["매우 불만족", "매우 만족"],
        options: [
          { value: "1", label: "매우 불만족" },
          { value: "2", label: "불만족" },
          { value: "3", label: "보통" },
          { value: "4", label: "만족" },
          { value: "5", label: "매우 만족" },
        ],
      },
      { id: "q2", text: "가장 유용했던 기능은 무엇인가요?", type: "text", placeholder: "예: AI 대화, 캘린더, 맞춤 정보 등" },
      { id: "q3", text: "개선되었으면 하는 점이 있다면 알려주세요.", type: "text", placeholder: "자유롭게 적어주세요" },
      { id: "q4", text: "자유롭게 의견을 남겨주세요.", type: "text", placeholder: "자유 의견" },
    ],
  },
];

export function getCheckDefinition(id: string): CheckDefinition | undefined {
  return CHECK_DEFINITIONS.find((d) => d.id === id);
}
